apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: aws
  generationRules:
    - resourceTypes:
        - aws_ec2_security_groups
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
      slxs:
        - baseName: aws-c7n-tag-compliance
          qualifiers: ["account_id"]
          baseTemplateName: aws-c7n-tag-compliance
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: aws-c7n-tag-compliance-taskset.yaml