apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://PLACEHOLDER.jpg
  alias: AWS Security Hub findings in AWS Account {{match_resource.resource.account_id}}
  asMeasuredBy: The number of AWS Security Hub findings in AWS account {{match_resource.resource.account_id}}
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: List AWS Security Hub findings in the AWS account {{match_resource.resource.account_id}}
  additionalContext:
    region: "{{match_resource.resource.region}}"
    account_id: "{{match_resource.resource.account_id}}"