apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: http://IMAGE_URL_PLACEHOLDER
  alias: Checks for missing tags on AWS resources in AWS account {{match_resource.resource.account_id}}
  asMeasuredBy: The number of AWS resources missing required tags in AWS account {{match_resource.resource.account_id}}
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: The total count of AWS resources missing required tags in AWS account {{match_resource.resource.account_id}}
  additionalContext:
    region: "{{match_resource.resource.region}}"
    account_id: "{{match_resource.resource.account_id}}"