apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/aws/Resource-Icons_06072024/Res_Database/Res_Amazon-Aurora_Amazon-RDS-Instance_48.svg
  alias: AWS RDS Health For Region {{match_resource.resource.region}} in Account {{match_resource.resource.account_id}}
  asMeasuredBy: RDS instance configuration issues (unencrypted, publicly accessible, or have backups disabled) in region {{match_resource.resource.region}} and account {{match_resource.resource.account_id}}
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: Identify RDS instances that are unencrypted, publicly accessible, or have backups disabled
  additionalContext:
    region: "{{match_resource.resource.region}}"
    account_id: "{{match_resource.resource.account_id}}"