apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  location: {{default_location}}
  description: List publicly accessible security groups, unused EIPs, and ELBs in AWS region {{match_resource.resource.region}} and account {{match_resource.resource.account_id}}
  codeBundle:
    {% if repo_url %}
    repoUrl: {{repo_url}}
    {% else %}
    repoUrl: https://github.com/runwhen-contrib/rw-c7n-codecollection.git
    {% endif %}
    {% if ref %}
    ref: {{ref}}
    {% else %}
    ref: main
    {% endif %}
    pathToRobot: codebundles/aws-c7n-network-health/runbook.robot
  configProvided:
    - name: AWS_REGION
      value: "{{match_resource.resource.region}}"
    - name: AWS_ACCOUNT_ID
      value: "{{match_resource.resource.account_id}}"
  secretsProvided:
    - name: AWS_ACCESS_KEY_ID
      workspaceKey: {{custom.aws_access_key_id}}
    - name: AWS_SECRET_ACCESS_KEY
      workspaceKey: {{custom.aws_secret_access_key}}
